from enum import StrEnum


class ProjectStatus(StrEnum):
    PLANNING = "PLANNING"
    RESEARCH = "RESEARCH"
    SOLUTION_DESIGN = "SOLUTION_DESIGN"
    PROTOTYPE = "PROTOTYPE"
    TESTING = "TESTING"
    PILOT = "PILOT"
    IMPLEMENTATION = "IMPLEMENTATION"
    IMPACT_MONITORING = "IMPACT_MONITORING"
    COMPLETED = "COMPLETED"
    ON_HOLD = "ON_HOLD"
    NEEDS_REVISION = "NEEDS_REVISION"
    CANCELLED = "CANCELLED"


PROJECT_COLLECTION = "projects"
