import { Bot, Building2, CheckCircle, Factory, FlaskConical, HeartHandshake, Lightbulb, Rocket, Send, Users } from "lucide-react";
const steps = [
  ["Citizen", Users, "A citizen, NGO or community group identifies a real local problem."], ["Submit Challenge", Send, "Structured submission captures location, urgency, affected people and evidence."],
  ["AI Analysis", Bot, "Mock AI classifies category, risk, duplication and expertise required."], ["Government Validation", CheckCircle, "Admin validates feasibility, priority and public relevance."],
  ["Institute Matching", Building2, "Universities are matched by domain strength, mentors and team availability."], ["Solution Development", Lightbulb, "Multidisciplinary student and faculty teams build prototypes."],
  ["Industry Collaboration", Factory, "Industry contributes funding, mentors, cloud credits, equipment or pilots."], ["Prototype", FlaskConical, "The solution is tested in realistic community conditions."],
  ["Pilot", Rocket, "District teams deploy controlled pilots and collect evidence."], ["Social Impact", HeartHandshake, "Impact metrics track citizens benefited and implementation outcomes."]
];
export default function HowItWorks() {
  return <div className="mx-auto max-w-7xl px-4 py-6 sm:py-8"><h1 className="text-3xl font-semibold text-navy sm:text-4xl">How It Works</h1><p className="mt-2 text-sm leading-6 text-slate-600 sm:text-base">A transparent flow from citizen problem discovery to measured implementation.</p><div className="mt-6 pb-4 sm:mt-8 sm:overflow-x-auto"><div className="grid gap-3 sm:flex sm:min-w-max sm:items-stretch">{steps.map(([title,Icon,text],i)=><div key={title} className="grid gap-3 sm:flex sm:items-center"><article className="flex gap-4 rounded-2xl border bg-white p-4 text-left shadow-sm sm:w-56 sm:block sm:p-5 sm:text-center"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue/10 text-blue sm:mx-auto sm:h-12 sm:w-12"><Icon size={20}/></span><div><h2 className="font-semibold text-navy sm:mt-3">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-600 sm:mt-2">{text}</p></div></article>{i<steps.length-1 && <span className="hidden text-2xl text-slate-300 sm:inline">→</span>}</div>)}</div></div></div>;
}
