import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useImpactData } from "../../hooks/useImpactData.js";
import { adminService } from "../../services/adminService.js";
export default function ValidationQueue(){
  const { data } = useImpactData();
  const [rows,setRows]=useState([]);
  const [message,setMessage]=useState("");
  const [error,setError]=useState("");
  const [busy,setBusy]=useState("");
  useEffect(()=>setRows(data.challenges.filter(c=>["Submitted","Under Review"].includes(c.status))),[data.challenges]);
  const act=async(id,status)=>{setBusy(`${id}-${status}`);setError("");setMessage("");try{if(status==="Validated") await adminService.approveChallenge(id); else if(status==="Rejected") await adminService.rejectChallenge(id); else await adminService.requestInfo(id);setRows(r=>status==="Validated"||status==="Rejected"?r.filter(x=>x.id!==id):r.map(x=>x.id===id?{...x,status}:x));setMessage(`${id} moved to ${status}.`)}catch(err){setError(err?.response?.data?.message || err?.response?.data?.detail || "Unable to update challenge.")}finally{setBusy("")}};
  return <div className="min-w-0"><h1 className="text-3xl font-semibold tracking-tight text-navy md:text-4xl">Validation Queue</h1>{message&&<p className="mt-6 rounded-2xl bg-green/10 p-4 font-semibold text-green">{message}</p>}{error&&<p className="mt-6 rounded-2xl bg-red-50 p-4 font-semibold text-red-600">{error}</p>}<div className="scrollbar-thin mt-8 overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full min-w-[860px] text-left text-sm md:min-w-[980px]"><thead className="bg-slate-50 text-slate-500"><tr>{["Challenge ID","Title","Category","District","AI Priority Score","Submitted Date","Action"].map(h=><th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody>{rows.map(c=><tr key={c.id} className="border-t"><td className="px-5 py-4 font-bold text-blue">{c.id}</td><td className="max-w-72 px-5 py-4 font-semibold text-navy">{c.title}</td><td className="px-5 py-4">{c.category}</td><td className="px-5 py-4">{c.district}</td><td className="px-5 py-4">{c.priority==="Critical"?94:c.priority==="High"?86:70}</td><td className="px-5 py-4">{c.date}</td><td className="px-5 py-4"><div className="flex flex-col gap-2 lg:flex-row"><Link to={`/admin/review/${c.id}`} className="rounded-xl border px-3 py-2 text-center font-semibold text-blue">View</Link><button disabled={!!busy} onClick={()=>act(c.id,"Validated")} className="rounded-xl bg-green px-3 py-2 font-semibold text-white disabled:opacity-60">{busy===`${c.id}-Validated`?"Saving...":"Approve"}</button><button disabled={!!busy} onClick={()=>act(c.id,"Rejected")} className="rounded-xl bg-red-600 px-3 py-2 font-semibold text-white disabled:opacity-60">Reject</button><button disabled={!!busy} onClick={()=>act(c.id,"Under Review")} className="rounded-xl bg-orange px-3 py-2 font-semibold text-white disabled:opacity-60">Request Info</button></div></td></tr>)}</tbody></table></div></div>
}
