import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, BarChart, Bar, PieChart, Pie, Cell } from "recharts";
import { Building2, CheckCircle, ClipboardList, Factory, FolderKanban, Hourglass, ListChecks, Trophy } from "lucide-react";
import { chartData } from "../../data/mockData.js";
import KPICard from "../../components/dashboard/KPICard.jsx";
import ChartCard from "../../components/charts/ChartCard.jsx";
const cards = [["Total Challenges","1,248","all submissions",ClipboardList],["Pending Validation","176","queue load",Hourglass],["Validated","824","approved",CheckCircle],["Assigned","338","with teams",ListChecks],["Active Projects","176","live work",FolderKanban],["Completed Projects","93","implemented",Trophy],["Institutes","64","partners",Building2],["Industries","41","partners",Factory]];
export default function AdminDashboard(){return <div><Header eyebrow="Welcome back" title="Admin Dashboard" text="Monitor societal challenges, collaborations and district-level impact."/><div className="mt-8 grid gap-6 sm:grid-cols-2 xl:grid-cols-4">{cards.map(c=><KPICard key={c[0]} title={c[0]} value={c[1]} note={c[2]} icon={c[3]}/>)}</div><div className="mt-10 grid gap-8 xl:grid-cols-[1fr_.72fr]"><section className="rounded-2xl border border-amber-100 bg-amber-50 p-6 shadow-sm md:p-7"><h2 className="text-lg font-semibold text-navy md:text-xl">Requires Attention</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{["12 High Priority Challenges","8 Awaiting Validation","4 Projects Delayed"].map((x,i)=><div key={x} className={`rounded-2xl border bg-white p-5 ${i===0?"text-red-600":"text-orange"}`}><p className="text-3xl font-semibold">{x.split(" ")[0]}</p><p className="mt-2 text-sm text-slate-600">{x.replace(x.split(" ")[0],"")}</p></div>)}</div></section><ImpactScore/></div><div className="mt-10 grid gap-8 xl:grid-cols-2"><ChartCard title="Challenge Activity"><ResponsiveContainer><LineChart data={chartData.monthly}><XAxis dataKey="month"/><YAxis/><Tooltip/><Line dataKey="submissions" stroke="#2563EB" strokeWidth={3}/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Category Distribution"><ResponsiveContainer><BarChart data={chartData.category}><XAxis dataKey="name" hide/><YAxis/><Tooltip/><Bar dataKey="value" fill="#2563EB"/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="District Distribution"><ResponsiveContainer><BarChart data={chartData.district}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="challenges" fill="#0D9488"/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Project Pipeline"><ResponsiveContainer><PieChart><Pie data={chartData.status} dataKey="value" innerRadius={60} outerRadius={95}>{chartData.status.map((_,i)=><Cell key={i} fill={["#2563EB","#0891B2","#7C3AED","#D97706","#16A34A"][i%5]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></ChartCard></div></div>}
function Header({eyebrow,title,text}){return <div className="flex flex-col gap-6 rounded-2xl border bg-white p-6 shadow-sm md:flex-row md:items-center md:justify-between md:p-8"><div className="min-w-0"><p className="text-sm font-semibold text-blue">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-navy md:text-4xl">{title}</h1><p className="mt-2 text-sm leading-7 text-slate-500 md:text-base">{text}</p></div><div className="grid gap-3 sm:grid-cols-3 md:flex md:flex-wrap"><button className="min-h-11 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold text-slate-600">Date Range</button><button className="min-h-11 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold text-slate-600">Export</button><button className="impact-gradient min-h-11 rounded-xl px-4 py-2.5 text-sm font-semibold text-white">+ New Challenge</button></div></div>}
function ImpactScore(){return <section className="premium-card rounded-2xl border p-6 md:p-7"><div className="flex flex-col gap-6 min-[380px]:flex-row min-[380px]:items-center"><div className="grid h-28 w-28 shrink-0 place-items-center rounded-full border border-blue/20 bg-[conic-gradient(#2563eb_0_87%,#e2e8f0_87%)]"><div className="grid h-20 w-20 place-items-center rounded-full bg-white"><span className="text-3xl font-semibold text-navy">87</span></div></div><div className="min-w-0"><p className="text-xs uppercase tracking-[0.2em] text-slate-500">Impact Score</p>{["Community Reach 92","Sustainability 84","Scalability 88","Innovation 85"].map(x=><p key={x} className="mt-3 text-sm text-slate-600">{x}</p>)}</div></div></section>}
