import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, BarChart, Bar, PieChart, Pie, Cell } from "recharts";
import { Building2, CheckCircle, ClipboardList, Factory, FolderKanban, Hourglass, ListChecks, Trophy } from "lucide-react";
import { chartData } from "../../data/mockData.js";
import KPICard from "../../components/dashboard/KPICard.jsx";
import ChartCard from "../../components/charts/ChartCard.jsx";
const cards = [["Total Challenges","1,248","all submissions",ClipboardList],["Pending Validation","176","queue load",Hourglass],["Validated","824","approved",CheckCircle],["Assigned","338","with teams",ListChecks],["Active Projects","176","live work",FolderKanban],["Completed Projects","93","implemented",Trophy],["Institutes","64","partners",Building2],["Industries","41","partners",Factory]];
export default function AdminDashboard(){return <div><Header eyebrow="Welcome back" title="Admin Dashboard" text="Monitor societal challenges, collaborations and district-level impact."/><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(c=><KPICard key={c[0]} title={c[0]} value={c[1]} note={c[2]} icon={c[3]}/>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_.72fr]"><section className="premium-card rounded-2xl border p-5"><h2 className="text-xl font-semibold text-navy">Requires Attention</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{["12 High Priority Challenges","8 Awaiting Validation","4 Projects Delayed"].map((x,i)=><div key={x} className={`rounded-2xl border p-4 ${i===0?"border-red-500/20 bg-red-500/10 text-red-400":"border-orange/20 bg-orange/10 text-orange"}`}><p className="text-2xl font-semibold">{x.split(" ")[0]}</p><p className="mt-1 text-sm">{x.replace(x.split(" ")[0],"")}</p></div>)}</div></section><ImpactScore/></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><ChartCard title="Challenge Activity"><ResponsiveContainer><LineChart data={chartData.monthly}><XAxis dataKey="month"/><YAxis/><Tooltip/><Line dataKey="submissions" stroke="#38BDF8" strokeWidth={3}/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Category Distribution"><ResponsiveContainer><BarChart data={chartData.category}><XAxis dataKey="name" hide/><YAxis/><Tooltip/><Bar dataKey="value" fill="#38BDF8"/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="District Distribution"><ResponsiveContainer><BarChart data={chartData.district}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="challenges" fill="#14B8A6"/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Project Pipeline"><ResponsiveContainer><PieChart><Pie data={chartData.status} dataKey="value" innerRadius={60} outerRadius={95}>{chartData.status.map((_,i)=><Cell key={i} fill={["#38BDF8","#14B8A6","#8B5CF6","#F59E0B","#22C55E"][i%5]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></ChartCard></div></div>}
function Header({eyebrow,title,text}){return <div className="flex flex-col gap-4 rounded-2xl border bg-[#08111f]/70 p-5 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-semibold text-blue">{eyebrow}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-navy">{title}</h1><p className="mt-1 text-slate-500">{text}</p></div><div className="flex flex-wrap gap-2"><button className="rounded-xl border px-3 py-2 text-sm font-semibold text-slate-600">Date Range</button><button className="rounded-xl border px-3 py-2 text-sm font-semibold text-slate-600">Export</button><button className="impact-gradient rounded-xl px-3 py-2 text-sm font-semibold text-[#041016]">+ New Challenge</button></div></div>}
function ImpactScore(){return <section className="premium-card rounded-2xl border p-5"><div className="flex items-center gap-5"><div className="grid h-28 w-28 place-items-center rounded-full border border-blue/25 bg-[conic-gradient(#38bdf8_0_87%,rgba(148,163,184,.1)_87%)]"><div className="grid h-20 w-20 place-items-center rounded-full bg-[#0d1828]"><span className="text-3xl font-semibold text-navy">87</span></div></div><div><p className="text-xs uppercase tracking-[0.2em] text-slate-500">Impact Score</p>{["Community Reach 92","Sustainability 84","Scalability 88","Innovation 85"].map(x=><p key={x} className="mt-2 text-sm text-slate-600">{x}</p>)}</div></div></section>}
