import { Bot, Building2, CheckCircle, Factory, FlaskConical, HeartHandshake, Lightbulb, Rocket, Send, Users } from "lucide-react";
const steps = [
  ["Citizen", Users, "A citizen, NGO or community group identifies a real local problem."], ["Submit Challenge", Send, "Structured submission captures location, urgency, affected people and evidence."],
  ["AI Analysis", Bot, "Mock AI classifies category, risk, duplication and expertise required."], ["Government Validation", CheckCircle, "Admin validates feasibility, priority and public relevance."],
  ["Institute Matching", Building2, "Universities are matched by domain strength, mentors and team availability."], ["Solution Development", Lightbulb, "Multidisciplinary student and faculty teams build prototypes."],
  ["Industry Collaboration", Factory, "Industry contributes funding, mentors, cloud credits, equipment or pilots."], ["Prototype", FlaskConical, "The solution is tested in realistic community conditions."],
  ["Pilot", Rocket, "District teams deploy controlled pilots and collect evidence."], ["Social Impact", HeartHandshake, "Impact metrics track citizens benefited and implementation outcomes."]
];
export default function HowItWorks() {
  return <div className="mx-auto max-w-[1440px] px-4 py-10 sm:px-6 md:py-12 lg:px-10 xl:px-12"><h1 className="text-3xl font-semibold tracking-tight text-navy md:text-4xl">How It Works</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-600 md:text-base">A transparent flow from citizen problem discovery to measured implementation.</p><div className="mt-10 pb-4 lg:overflow-x-auto"><div className="grid gap-5 lg:flex lg:min-w-max lg:items-stretch">{steps.map(([title,Icon,text],i)=><div key={title} className="grid gap-4 lg:flex lg:items-center"><article className="flex gap-5 rounded-2xl border bg-white p-6 text-left shadow-sm lg:block lg:w-60 lg:p-7 lg:text-center"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-blue/10 text-blue lg:mx-auto"><Icon size={21}/></span><div><h2 className="text-lg font-semibold text-navy lg:mt-4">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div></article>{i<steps.length-1 && <span className="hidden text-2xl text-slate-300 lg:inline">→</span>}</div>)}</div></div></div>;
}
